%MATLAB Code from Sensor Array Analyzer App

%Generated by MATLAB 9.2 and Phased Array System Toolbox 3.4

%Generated on 17-Sep-2017 14:12:02

% Create a uniform rectangular array
h = phased.URA;
h.Size = [6 6];
h.ElementSpacing = [0.008 0.008];
h.Lattice = 'Rectangular';
h.ArrayNormal = 'x';
%Calculate Row Taper
rwind = ones(1,6);
rwind = repmat(rwind,6,1);
%Calculate Column Taper
cwind = ones(1,6);
cwind = repmat(cwind.',1,6);
%Calculate taper
wind = rwind.*cwind;
h.Taper = wind;
%Create Cardioid Microphone Element
el = phased.CustomMicrophoneElement;
el.PolarPatternFrequencies = [1000 2000];
el.PolarPattern = mag2db([...
    0.5+0.5*cosd(el.PolarPatternAngles);...
    0.6+0.4*cosd(el.PolarPatternAngles)]);
h.Element = el;
%Assign frequencies and propagation speed
F = 40000;
PS = 340;
%Create figure, panel, and axes
fig = figure;
panel = uipanel('Parent',fig);
hAxes = axes('Parent',panel,'Color','none');
viewArray(h,'AxesHandle',hAxes,'ShowNormals',false,'ShowIndex','None');
view(hAxes,[90 0]);
